# Generated by Django 6.0.7 on 2026-07-31 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenabook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='address',
        ),
        migrations.RemoveField(
            model_name='turf',
            name='city',
        ),
        migrations.RemoveField(
            model_name='turf',
            name='country',
        ),
        migrations.RemoveField(
            model_name='turf',
            name='description',
        ),
        migrations.RemoveField(
            model_name='turf',
            name='state',
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='venues/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arenabook.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arenabook.country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arenabook.state')),
            ],
        ),
        migrations.AddField(
            model_name='turf',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turfs', to='arenabook.venue'),
        ),
    ]
